# Generated by Django 5.0.1 on 2024-04-13 14:15

import django.db.models.deletion
import docs.models
import storages.backends.s3
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsArchive',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=docs.models.get_short_uuid, max_length=128, verbose_name='Наименование архива')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('predicted_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='Предсказаный класс')),
                ('file', models.FileField(null=True, storage=storages.backends.s3.S3Storage(), upload_to=docs.models.image_directory_path, verbose_name='Файл')),
                ('docs_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='docs.documentsarchive', verbose_name='Архив документов')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
