# Generated by Django 5.0.1 on 2024-04-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filename',
            field=models.TextField(blank=True, null=True),
        ),
    ]
